cat > crates/fractal-shard/Cargo.toml <<'EOF'
[package]
name = "fractal-shard"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
[dependencies]
dashmap = "6"
solana-sdk = { workspace = true }
EOF
